### ISSUE TITLE
oc8 first start of chat app with user_ldap

### ISSUE THREAD

**Issue by apg1980** [owncloud/chat#198] opened 2015-02-13 16:59 UTC
unable to use with ldap.

Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im Serverprotokoll gefunden werden.Fatal 	index 	Exception: {"Message":"An exception occurred while executing '\t\t\tINSERT\n\t\t\tINTO `oc_chat_och_users_in_conversation`\n\t\t\t(\n\t\t\t\t`user`,\n\t\t\t\t`conversation_id`,\n\t\t\t\t`joined`\n\t\t\t) VALUES (\n\t\t\t\t?,\n\t\t\t\t?,\n\t\t\t\t?\n\t\t\t)' with params [null, \"CONV_ID_1423846649_7\", 1423846649]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user' cannot be null","Code":0,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), '\\t\\t\\tINSERT\\n\\t\\t\\tIN...', Array)\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/db\/statementwrapper.php(65): Doctrine\\DBAL\\Statement->execute()\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/public\/appframework\/db\/mapper.php(213): OC_DB_StatementWrapper->execute()\n#4 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/db\/usermapper.php(124): OCP\\AppFramework\\Db\\Mapper->execute('\\t\\t\\tINSERT\\n\\t\\t\\tIN...', Array)\n#5 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/commands\/join.php(40): OCA\\Chat\\OCH\\Db\\UserMapper->insertUnique(Object(OCA\\Chat\\OCH\\Db\\User))\n#6 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/commands\/startconv.php(69): OCA\\Chat\\OCH\\Commands\\Join->execute()\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/och.php(75): OCA\\Chat\\OCH\\Commands\\StartConv->execute()\n#8 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/lib\/och\/och.php(17): OCA\\Chat\\OCH\\OCH->createInitConvs()\n#9 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/app\/chat.php(447): OCA\\Chat\\OCH\\OCH->getInitConvs()\n#10 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/chat\/controller\/appcontroller.php(58): OCA\\Chat\\App\\Chat->getInitConvs()\n#11 [internal function]: OCA\\Chat\\Controller\\AppController->index()\n#12 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#13 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Chat\\Controller\\AppController), 'index')\n#14 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Chat\\Controller\\AppController), 'index')\n#15 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('AppController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#16 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#17 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#18 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/chat\/')\n#19 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(36): OC::handleRequest()\n#20 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":112}

**Comment by LEDfan** [comment] 2015-02-22 06:33
Hi. This is a know bug with `user_ldap`. Duplicate of #128

**Closed by LEDfan** 2015-02-22 06:33 UTC
